name: CI Pipeline

env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    validate:
        name: Valida o Script
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: verifica a sintaxe do script
              run: |
                if ! bash -n status-check.sh; then
                echo "::error::Erro de sintaxe no script"
                exit 1
                else
                echo "::notice::Script válido"
                fi
    
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        needs: validate
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Testes
              run: |
                echo "Passou nos testes."
                exit 0

    package:
        name: Package Artifact
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Criando o arquivo de relatório
              run: echo "Texto padrão" > report.txt
            - name: Criando report.zip
              run: |
                zip -r report.zip report.txt
                echo "::warning::Certifique-se de revisar o conteúdo do relatório."
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: application-monitor-report
                path: report.zip
            - name: Job Summary
              run: |
                echo "### CI Summary" >> $GITHUB_STEP_SUMMARY
                echo "* Sistema operacional: \`${{ runner.os }}\`" >> $GITHUB_STEP_SUMMARY
                echo "* Branch: \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY