name: Deploy para Produção

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    deploy:
        name: Simular Deploy
        runs-on: ubuntu-latest
        environment:
            name: production
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Simular Deploy
              run: |
                echo "Iniciando o deploy: ${{ vars.PROD_DOMAIN }}"
                echo "Simulando deploy..."
                sleep 5
                echo "Deploy concluído: ${{ vars.PROD_DOMAIN }}."